---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: dex
data:
  config.yaml: |
    issuer: http://dex.dex.svc.cluster.local:5556/dex

    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    staticClients:
      - id: redpanda
        name: Redpanda
        secret: redpanda-secret
        redirectURIs:
          - http://localhost:8080/callback

    enablePasswordDB: true
    staticPasswords:
      - email: user@example.com
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # password
        username: redpanda-user
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

    oauth2:
      passwordConnector: local
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.41.1
          command: ["dex", "serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: config
              mountPath: /etc/dex
      volumes:
        - name: config
          configMap:
            name: dex-config
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex
spec:
  selector:
    app: dex
  ports:
    - port: 5556
      targetPort: 5556
